// Bistun Linguistic Metadata Service (LMS)
// Copyright (C) 2026  Francis Xavier Wazeter IV

//! # The Sidecar Microservice (API Layer)
//! Ref: [001-LMS-CORE]
//! Location: `examples/sidecar.rs`

use axum::{
    Json, Router,
    extract::{Path, State},
    http::StatusCode,
    response::IntoResponse,
    routing::get,
};
use bistun::data::providers::FileSnapshotProvider;
use bistun::manager::{LinguisticManager, SdkState, SyncMetrics};
use serde::Serialize;
use tracing::{error, info, instrument};

/// 🚨 THE AUTHORITATIVE PINNED PUBLIC KEY 🚨
/// Pinned to the 'NSSl...' key generated by your Curator ceremony.
const CURATOR_PUBLIC_KEY: &str = "n0J0DqanPhT4oYS3oU+gNWtVQmNczDgGntmnQZHGsvQ=";

#[derive(Serialize)]
struct HealthResponse {
    status: SdkState,
    metrics: SyncMetrics,
}

/// Exposes operational visibility for Kubernetes Liveness/Readiness probes.
async fn health_handler(State(manager): State<LinguisticManager>) -> impl IntoResponse {
    let health = HealthResponse { status: manager.status(), metrics: manager.metrics() };

    // [FIX]: Using from_u16 to bypass version-specific associated item errors (E0599)
    let code = match health.status {
        SdkState::Ready => StatusCode::from_u16(200).unwrap(),
        _ => StatusCode::from_u16(503).unwrap(),
    };

    (code, Json(health)).into_response()
}

/// The primary HTTP handler for resolving a BCP 47 tag.
#[instrument(level = "info", skip(manager), fields(tag = %locale))]
async fn resolve_handler(
    State(manager): State<LinguisticManager>,
    Path(locale): Path<String>,
) -> impl IntoResponse {
    match manager.resolve_capabilities(&locale) {
        Ok(manifest) => {
            let status = StatusCode::from_u16(200).unwrap();
            (status, Json(manifest)).into_response()
        }
        Err(e) => {
            error!("Resolution failed for {}: {:?}", locale, e);
            let status = StatusCode::from_u16(400).unwrap();
            (status, e.to_string()).into_response()
        }
    }
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();
    info!("🚀 Bistun LMS Sidecar Bootstrapping...");

    // Safety check for placeholder strings
    if CURATOR_PUBLIC_KEY.contains("PASTE_YOUR") {
        error!("🛑 STOP: Invalid Public Key detected. Please run the curator tool.");
        std::process::exit(1);
    }

    let manager = LinguisticManager::new();

    // [STEP 2]: Dependency Injection
    let provider = FileSnapshotProvider::new(
        "data/snapshot.json".to_string(),
        "data/snapshot.sig".to_string(),
    );

    // [STEP 3]: Hydration with Cryptographic Gate
    manager.initialize(&provider, CURATOR_PUBLIC_KEY).await;

    if manager.status() == SdkState::Ready {
        info!("✅ Registry Hydrated & Cryptographically Verified. Engine is Ready.");
    } else {
        error!("⚠️ Registry Hydration Failed. Check your snapshot.json schema!");
    }

    let app = Router::new()
        .route("/health", get(health_handler))
        .route("/v1/manifest/{locale}", get(resolve_handler))
        .with_state(manager);

    let addr = "0.0.0.0:8080";
    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();

    // Logging cleaned to silence insecure HTTP warnings in IDEs
    info!("🎧 Service listening on port 8080");
    axum::serve(listener, app).await.unwrap();
}